# Generated by Django 2.2.2 on 2020-12-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(default='', max_length=100, null=True)),
                ('agent_email', models.CharField(default='', max_length=100, null=True)),
                ('agent_mobile', models.IntegerField(default=0)),
                ('agent_address', models.CharField(default='', max_length=250, null=True)),
                ('agent_state', models.CharField(default='', max_length=50, null=True)),
                ('agent_status', models.CharField(default='New', max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='KycAdmin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('kycadmin_name', models.CharField(default='', max_length=100, null=True)),
                ('kycadmin_email', models.CharField(default='', max_length=100, null=True)),
                ('kycadmin_mobile', models.IntegerField(default=0)),
                ('kycadmin_address', models.CharField(default='', max_length=250, null=True)),
                ('kycadmin_state', models.CharField(default='', max_length=50, null=True)),
                ('kycadmin_status', models.CharField(default='New', max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kyc_admin',
            },
        ),
        migrations.RemoveField(
            model_name='authusers',
            name='username',
        ),
        migrations.AddField(
            model_name='authusers',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authusers',
            name='password',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authusers',
            name='user_code',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authusers',
            name='useremail',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
