# Generated by Django 2.2.2 on 2020-12-31 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_auto_20201231_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='admin_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management_app.KycAdmin'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_status',
            field=models.CharField(default='active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kycadmin',
            name='kycadmin_status',
            field=models.CharField(default='active', max_length=50, null=True),
        ),
    ]
