# Generated by Django 2.2.2 on 2021-01-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0005_auto_20210102_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_mobile',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='kycadmin',
            name='kycadmin_mobile',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
