# Generated by Django 2.2.2 on 2021-01-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0006_auto_20210103_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_mobile',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='kycadmin',
            name='kycadmin_mobile',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
