# Generated by Django 2.2.2 on 2021-01-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0008_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(default='', max_length=100, null=True)),
                ('client_usercode', models.CharField(default='', max_length=100, null=True)),
                ('client_email', models.CharField(default='', max_length=100, null=True)),
                ('client_mobile', models.CharField(default='', max_length=10, null=True)),
                ('client_address', models.CharField(default='', max_length=250, null=True)),
                ('client_state', models.CharField(default='', max_length=50, null=True)),
                ('client_status', models.CharField(default='new', max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
