# Generated by Django 2.2.2 on 2021-01-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0009_auto_20210104_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_status',
            field=models.CharField(default='New', max_length=50, null=True),
        ),
    ]
