# Generated by Django 2.2.2 on 2021-01-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0010_auto_20210104_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='check_by_agent_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='check_uncheck_status',
            field=models.BooleanField(default=False),
        ),
    ]
