# Generated by Django 2.2.2 on 2021-01-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0012_clients_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='checked_time',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
