# Generated by Django 2.2.2 on 2021-01-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0013_clients_checked_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='check_by_agent_id',
        ),
    ]
